import { v4 as uuidv4 } from 'uuid';
export const teachers = [
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
  {
    id: uuidv4(),
    nameSur: "Emin Resulzade",
    phone: "0551231234",
    email: "example@org",
    qeydiyyatTarixi: "2022-01-01",
    cariGroups: "lorem",
    image: "../../imgs/profile-photo.jpeg",
  },
];
